package com.monzag;

public enum Options {
    EXIT,
    SUM_OF_PROFITS,
    PROFITS_BY_DATA,
    AMOUNT_OF_RESERVATION_AT_DAY,
    AMOUNT_OF_RESERVATION_AT_MONTH,
    RESERVATIONS_BY_DATA,
    RESERVATIONS_BY_PERSON,
    RESERVATIONS_BY_MOVIE,
    RUSH_HOURS,
    CHEAPEST_TICKET,
    MOST_EXPENSIVE_TICKET
}
